# Generated by Django 3.2.13 on 2022-06-14 11:53

import Ticket.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Up_File',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/', validators=[Ticket.validators.validate_file_size, Ticket.validators.validate_file_extension], verbose_name=''),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='Up_Doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/', validators=[Ticket.validators.validate_file_size, Ticket.validators.validate_file_extension], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=10, null=True),
        ),
    ]
