# Generated by Django 3.2.13 on 2022-06-17 03:20

import Ticket.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_auto_20220616_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Up_File',
            field=models.FileField(blank=True, help_text='This field is not required', null=True, upload_to='dokumen/', validators=[Ticket.validators.validate_file_size, Ticket.validators.validate_file_extension], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='Up_Doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/comment/', validators=[Ticket.validators.validate_file_size, Ticket.validators.validate_file_extension], verbose_name=''),
        ),
    ]
