# Generated by Django 3.2.14 on 2022-07-05 05:33

import Ticket.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_auto_20220617_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Description',
            field=models.CharField(help_text='Describe your problem here!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Subject',
            field=models.CharField(help_text='The subject of your problem or question', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Up_File',
            field=models.FileField(blank=True, help_text='This field is not required', null=True, upload_to='dokumen/', validators=[Ticket.validators.validate_file_size, Ticket.validators.validate_file_extension1], verbose_name=''),
        ),
    ]
